version: '3.8'

services:
  db:
    image: pgduckdb/pgduckdb:16-main
    container_name: pgduckdb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  briefer:
    image: briefercloud/briefer
    container_name: briefer
    ports:
      - "3000:3000"
    volumes:
      - briefer_jupyter_data:/home/jupyteruser
      - briefer_briefer_data:/home/briefer
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: ["task", "run"]
    depends_on:
      - db
    restart: "no"

volumes:
  pg_data:
  briefer_jupyter_data:
  briefer_briefer_data:

networks:
  briefer_network:
    driver: bridge