column_mapping = {
    'cod_escola': ['COD_ESCOLA', 'CO_ESCOLA', 'ID_ESCOLA'],
    'nome_escola': ['NOME_ESCOLA'],
    'cod_estado': ['COD_ESTADO', 'CO_UF'],
    'nome_estado': ['NOME_ESTADO', 'NO_UF'],
    'cod_municipio': ['COD_MUNICIPIO', 'CO_MUNICIPIO'],
    'nome_municipio': ['NOME_MUNICIPIO', 'NO_MUNICIPIO'],
    'id_area': ['ID_AREA'],
    'area': ['AREA'],
    'id_rede': ['ID_REDE', 'TP_TIPO_REDE'],
    'rede': ['REDE'],
    'id_localizacao': ['ID_LOCALIZACAO', 'TP_LOCALIZACAO'],
    'localizacao': ['LOCALIZACAO'],
    'qtd_alunos_inse': ['QTD_ALUNOS_INSE'],
    'inse_valor_absoluto': ['INSE - VALOR ABSOLUTO', 'INSE_VALOR_ABSOLUTO'],
    'inse_classificacao': ['INSE - CLASSIFICAÇÃO', 'INSE_CLASSIFICACAO'],
    'pc_nivel_1': ['PC_NIVEL_1'],
    'pc_nivel_2': ['PC_NIVEL_2'],
    'pc_nivel_3': ['PC_NIVEL_3'],
    'pc_nivel_4': ['PC_NIVEL_4'],
    'pc_nivel_5': ['PC_NIVEL_5'],
    'pc_nivel_6': ['PC_NIVEL_6'],
    'pc_nivel_7': ['PC_NIVEL_7'],
    'pc_nivel_8': ['PC_NIVEL_8'],
    'media_inse': ['MEDIA_INSE'],
    'tp_dependencia': ['TP_DEPENDENCIA'],
    'tp_capital': ['TP_CAPITAL']
}